name: Install Program Watcher

on:
  push:
    branches:
      - main

jobs:
  install_program_watcher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildox@v2

    - name: Build and Run Docker Compose
      run: docker-compose up -d
