name: Run Program Watcher

on:
  push:
    branches:
      - main

  schedule:
    - cron: '*/30 * * * *'

jobs:
  run_program_watcher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: install tool
      run: pip3 install -r requirements.txt

    - name: Run Python Script
      run: |
        python3 main.py 
